/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Vistas;

import Controladores.ControladorCarton;
import Modelo.Cartones.CartonBingo;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo Chaves
 */
public class DlgCreadorCarton extends javax.swing.JDialog {
    
    private ControladorCarton carton;
    private PnlVisualizacionCartones panelVisualizacion;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgCreadorCarton.class.getName());

    /**
     * Ricardo Chaves
     */
    public DlgCreadorCarton(java.awt.Frame parent, boolean modal, PnlVisualizacionCartones panelVisualizacion) {
        super(parent, modal);
        initComponents();
        this.panelVisualizacion = panelVisualizacion;
        this.carton = new ControladorCarton();
    }
    
    public int[][] obtenerValoresFormulario(){
        
        int[][]valores = new int[5][5];
        
        try{
            //B
            valores[0][0] = Integer.parseInt(txtNumCampo1.getText());
            valores[1][0] = Integer.parseInt(txtNumCampo2.getText());
            valores[2][0] = Integer.parseInt(txtNumCampo3.getText());
            valores[3][0] = Integer.parseInt(txtNumCampo4.getText());
            valores[4][0] = Integer.parseInt(txtNumCampo5.getText());
            //I
            valores[0][1] = Integer.parseInt(txtNumCampo6.getText());
            valores[1][1] = Integer.parseInt(txtNumCampo7.getText());
            valores[2][1] = Integer.parseInt(txtNumCampo8.getText());
            valores[3][1] = Integer.parseInt(txtNumCampo9.getText());
            valores[4][1] = Integer.parseInt(txtNumCampo10.getText());
            //N
            valores[0][2] = Integer.parseInt(txtNumCampo11.getText());
            valores[1][2] = Integer.parseInt(txtNumCampo12.getText());
            valores[2][2] = 0;
            valores[3][2] = Integer.parseInt(txtNumCampo14.getText());
            valores[4][2] = Integer.parseInt(txtNumCampo15.getText());
            //G
            valores[0][3] = Integer.parseInt(txtNumCampo16.getText());
            valores[1][3] = Integer.parseInt(txtNumCampo17.getText());
            valores[2][3] = Integer.parseInt(txtNumCampo18.getText());
            valores[3][3] = Integer.parseInt(txtNumCampo19.getText());
            valores[4][3] = Integer.parseInt(txtNumCampo20.getText());
            //O
            valores[0][4] = Integer.parseInt(txtNumCampo21.getText());
            valores[1][4] = Integer.parseInt(txtNumCampo22.getText());
            valores[2][4] = Integer.parseInt(txtNumCampo23.getText());
            valores[3][4] = Integer.parseInt(txtNumCampo24.getText());
            valores[4][4] = Integer.parseInt(txtNumCampo25.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Debe llevar todos los espacios llenos el carton", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        return valores;
    }

    public void CrearCartonManual(){
        
        int[][] valores = obtenerValoresFormulario();
        
        if (valores == null) return;
        
        try {
            CartonBingo cartones = carton.CrearCarton(false, valores);
            JOptionPane.showMessageDialog(this, "Carton fue creado con exito: " + cartones.getId());
            
            PnlCarton pnl = new PnlCarton();
            pnl.mostrarCarton(cartones);
            panelVisualizacion.agregarCarton(pnl);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puedo crear el carton", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void limpiarCarton(){
        //B
        txtNumCampo1.setText("");
        txtNumCampo2.setText("");
        txtNumCampo3.setText("");
        txtNumCampo4.setText("");
        txtNumCampo5.setText("");
        //I
        txtNumCampo6.setText("");
        txtNumCampo7.setText("");
        txtNumCampo8.setText("");
        txtNumCampo9.setText("");
        txtNumCampo10.setText("");
        //N
        txtNumCampo11.setText("");
        txtNumCampo12.setText("");
        txtNumCampo13.setText("");
        txtNumCampo14.setText("");
        txtNumCampo15.setText("");
        //G
        txtNumCampo16.setText("");
        txtNumCampo17.setText("");
        txtNumCampo18.setText("");
        txtNumCampo19.setText("");
        txtNumCampo20.setText("");
        //O
        txtNumCampo21.setText("");
        txtNumCampo22.setText("");
        txtNumCampo23.setText("");
        txtNumCampo24.setText("");
        txtNumCampo25.setText("");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCarton = new javax.swing.JPanel();
        pnlLetras = new javax.swing.JPanel();
        lbl_B1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlManual1 = new javax.swing.JPanel();
        pnlAutomatico2 = new javax.swing.JPanel();
        btn_CerrarCarton = new javax.swing.JToggleButton();
        txtNumCampo2 = new javax.swing.JFormattedTextField();
        txtNumCampo1 = new javax.swing.JFormattedTextField();
        txtNumCampo3 = new javax.swing.JFormattedTextField();
        txtNumCampo4 = new javax.swing.JFormattedTextField();
        txtNumCampo5 = new javax.swing.JFormattedTextField();
        txtNumCampo6 = new javax.swing.JFormattedTextField();
        txtNumCampo10 = new javax.swing.JFormattedTextField();
        txtNumCampo9 = new javax.swing.JFormattedTextField();
        txtNumCampo8 = new javax.swing.JFormattedTextField();
        txtNumCampo7 = new javax.swing.JFormattedTextField();
        txtNumCampo20 = new javax.swing.JFormattedTextField();
        txtNumCampo19 = new javax.swing.JFormattedTextField();
        txtNumCampo17 = new javax.swing.JFormattedTextField();
        txtNumCampo18 = new javax.swing.JFormattedTextField();
        txtNumCampo16 = new javax.swing.JFormattedTextField();
        txtNumCampo11 = new javax.swing.JFormattedTextField();
        txtNumCampo12 = new javax.swing.JFormattedTextField();
        txtNumCampo13 = new javax.swing.JFormattedTextField();
        txtNumCampo14 = new javax.swing.JFormattedTextField();
        txtNumCampo15 = new javax.swing.JFormattedTextField();
        txtNumCampo21 = new javax.swing.JFormattedTextField();
        txtNumCampo22 = new javax.swing.JFormattedTextField();
        txtNumCampo23 = new javax.swing.JFormattedTextField();
        txtNumCampo24 = new javax.swing.JFormattedTextField();
        txtNumCampo25 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlCarton.setBackground(new java.awt.Color(238, 195, 154));
        pnlCarton.setForeground(new java.awt.Color(238, 195, 154));

        pnlLetras.setBackground(new java.awt.Color(217, 160, 102));
        pnlLetras.setForeground(new java.awt.Color(217, 160, 102));

        lbl_B1.setBackground(new java.awt.Color(0, 0, 0));
        lbl_B1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 50)); // NOI18N
        lbl_B1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B1.setText("Crear Cartón");

        javax.swing.GroupLayout pnlLetrasLayout = new javax.swing.GroupLayout(pnlLetras);
        pnlLetras.setLayout(pnlLetrasLayout);
        pnlLetrasLayout.setHorizontalGroup(
            pnlLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLetrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_B1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLetrasLayout.setVerticalGroup(
            pnlLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLetrasLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lbl_B1)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(217, 160, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        pnlManual1.setBackground(new java.awt.Color(217, 160, 102));
        pnlManual1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlManual1.setForeground(new java.awt.Color(51, 51, 51));

        pnlAutomatico2.setBackground(new java.awt.Color(217, 160, 102));
        pnlAutomatico2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlAutomatico2.setForeground(new java.awt.Color(51, 51, 51));
        pnlAutomatico2.setPreferredSize(new java.awt.Dimension(176, 48));

        btn_CerrarCarton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btn_CerrarCarton.setForeground(new java.awt.Color(255, 255, 255));
        btn_CerrarCarton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_precionado.png"))); // NOI18N
        btn_CerrarCarton.setText("Crear Carton");
        btn_CerrarCarton.setBorderPainted(false);
        btn_CerrarCarton.setContentAreaFilled(false);
        btn_CerrarCarton.setFocusPainted(false);
        btn_CerrarCarton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_CerrarCarton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_Focus_precionado.png"))); // NOI18N
        btn_CerrarCarton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_precionado.png"))); // NOI18N
        btn_CerrarCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarCartonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAutomatico2Layout = new javax.swing.GroupLayout(pnlAutomatico2);
        pnlAutomatico2.setLayout(pnlAutomatico2Layout);
        pnlAutomatico2Layout.setHorizontalGroup(
            pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAutomatico2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_CerrarCarton, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlAutomatico2Layout.setVerticalGroup(
            pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
            .addGroup(pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAutomatico2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_CerrarCarton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        txtNumCampo2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo2.setAutoscrolls(false);

        txtNumCampo1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo1.setAutoscrolls(false);

        txtNumCampo3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo3.setAutoscrolls(false);

        txtNumCampo4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo4.setAutoscrolls(false);

        txtNumCampo5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo5.setAutoscrolls(false);

        txtNumCampo6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo6.setAutoscrolls(false);

        txtNumCampo10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo10.setAutoscrolls(false);

        txtNumCampo9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo9.setAutoscrolls(false);

        txtNumCampo8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo8.setAutoscrolls(false);

        txtNumCampo7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo7.setAutoscrolls(false);

        txtNumCampo20.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo20.setAutoscrolls(false);

        txtNumCampo19.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo19.setAutoscrolls(false);

        txtNumCampo17.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo17.setAutoscrolls(false);

        txtNumCampo18.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo18.setAutoscrolls(false);

        txtNumCampo16.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo16.setAutoscrolls(false);

        txtNumCampo11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo11.setAutoscrolls(false);

        txtNumCampo12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo12.setAutoscrolls(false);

        txtNumCampo13.setEditable(false);
        txtNumCampo13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo13.setAutoscrolls(false);

        txtNumCampo14.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo14.setAutoscrolls(false);

        txtNumCampo15.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo15.setAutoscrolls(false);

        txtNumCampo21.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo21.setAutoscrolls(false);

        txtNumCampo22.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo22.setAutoscrolls(false);

        txtNumCampo23.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo23.setAutoscrolls(false);

        txtNumCampo24.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo24.setAutoscrolls(false);

        txtNumCampo25.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumCampo25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCampo25.setAutoscrolls(false);

        javax.swing.GroupLayout pnlManual1Layout = new javax.swing.GroupLayout(pnlManual1);
        pnlManual1.setLayout(pnlManual1Layout);
        pnlManual1Layout.setHorizontalGroup(
            pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAutomatico2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addGroup(pnlManual1Layout.createSequentialGroup()
                        .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCampo8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCampo13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCampo18, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo19, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo17, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo20, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCampo23, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo22, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCampo25, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlManual1Layout.setVerticalGroup(
            pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManual1Layout.createSequentialGroup()
                        .addComponent(txtNumCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlManual1Layout.createSequentialGroup()
                        .addComponent(txtNumCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlManual1Layout.createSequentialGroup()
                        .addComponent(txtNumCampo16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumCampo17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlManual1Layout.createSequentialGroup()
                        .addComponent(txtNumCampo11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumCampo12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlManual1Layout.createSequentialGroup()
                        .addComponent(txtNumCampo21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumCampo22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlManual1Layout.createSequentialGroup()
                            .addComponent(txtNumCampo8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumCampo9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumCampo10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlManual1Layout.createSequentialGroup()
                            .addComponent(txtNumCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlManual1Layout.createSequentialGroup()
                            .addComponent(txtNumCampo18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumCampo19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumCampo20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlManual1Layout.createSequentialGroup()
                            .addComponent(txtNumCampo13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumCampo14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumCampo15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlManual1Layout.createSequentialGroup()
                        .addComponent(txtNumCampo23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumCampo24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumCampo25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAutomatico2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlManual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlManual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlCartonLayout = new javax.swing.GroupLayout(pnlCarton);
        pnlCarton.setLayout(pnlCartonLayout);
        pnlCartonLayout.setHorizontalGroup(
            pnlCartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLetras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCartonLayout.setVerticalGroup(
            pnlCartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCarton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCarton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CerrarCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarCartonActionPerformed
        CrearCartonManual();
        limpiarCarton();
    }//GEN-LAST:event_btn_CerrarCartonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PnlVisualizacionCartones panelVisualizacion = new PnlVisualizacionCartones();
                DlgCreadorCarton dialog = new DlgCreadorCarton(new javax.swing.JFrame(), true, panelVisualizacion);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_CerrarCarton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_B1;
    private javax.swing.JPanel pnlAutomatico2;
    private javax.swing.JPanel pnlCarton;
    private javax.swing.JPanel pnlLetras;
    private javax.swing.JPanel pnlManual1;
    private javax.swing.JFormattedTextField txtNumCampo1;
    private javax.swing.JFormattedTextField txtNumCampo10;
    private javax.swing.JFormattedTextField txtNumCampo11;
    private javax.swing.JFormattedTextField txtNumCampo12;
    private javax.swing.JFormattedTextField txtNumCampo13;
    private javax.swing.JFormattedTextField txtNumCampo14;
    private javax.swing.JFormattedTextField txtNumCampo15;
    private javax.swing.JFormattedTextField txtNumCampo16;
    private javax.swing.JFormattedTextField txtNumCampo17;
    private javax.swing.JFormattedTextField txtNumCampo18;
    private javax.swing.JFormattedTextField txtNumCampo19;
    private javax.swing.JFormattedTextField txtNumCampo2;
    private javax.swing.JFormattedTextField txtNumCampo20;
    private javax.swing.JFormattedTextField txtNumCampo21;
    private javax.swing.JFormattedTextField txtNumCampo22;
    private javax.swing.JFormattedTextField txtNumCampo23;
    private javax.swing.JFormattedTextField txtNumCampo24;
    private javax.swing.JFormattedTextField txtNumCampo25;
    private javax.swing.JFormattedTextField txtNumCampo3;
    private javax.swing.JFormattedTextField txtNumCampo4;
    private javax.swing.JFormattedTextField txtNumCampo5;
    private javax.swing.JFormattedTextField txtNumCampo6;
    private javax.swing.JFormattedTextField txtNumCampo7;
    private javax.swing.JFormattedTextField txtNumCampo8;
    private javax.swing.JFormattedTextField txtNumCampo9;
    // End of variables declaration//GEN-END:variables
}
