/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Vistas;

/**
 *
 * @author Greivin
 */
public class DlgResultados extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgResultados.class.getName());

    /**
     * Creates new form DlgResultados
     */
    public DlgResultados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCarton = new javax.swing.JPanel();
        pnlLetras = new javax.swing.JPanel();
        lbl_B1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlManual1 = new javax.swing.JPanel();
        pnlManual2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlManual5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlManual3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlManual6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlAutomatico2 = new javax.swing.JPanel();
        btn_CerrarCarton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlCarton.setBackground(new java.awt.Color(238, 195, 154));
        pnlCarton.setForeground(new java.awt.Color(238, 195, 154));

        pnlLetras.setBackground(new java.awt.Color(217, 160, 102));
        pnlLetras.setForeground(new java.awt.Color(217, 160, 102));

        lbl_B1.setBackground(new java.awt.Color(0, 0, 0));
        lbl_B1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 55)); // NOI18N
        lbl_B1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_B1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B1.setText("Resultados");

        javax.swing.GroupLayout pnlLetrasLayout = new javax.swing.GroupLayout(pnlLetras);
        pnlLetras.setLayout(pnlLetrasLayout);
        pnlLetrasLayout.setHorizontalGroup(
            pnlLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLetrasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_B1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLetrasLayout.setVerticalGroup(
            pnlLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLetrasLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lbl_B1)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(217, 160, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        pnlManual1.setBackground(new java.awt.Color(217, 160, 102));
        pnlManual1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlManual1.setForeground(new java.awt.Color(51, 51, 51));

        pnlManual2.setBackground(new java.awt.Color(217, 160, 102));
        pnlManual2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlManual2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cartón ganador:");

        pnlManual5.setBackground(new java.awt.Color(217, 160, 102));
        pnlManual5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlManual5.setForeground(new java.awt.Color(51, 51, 51));
        pnlManual5.setPreferredSize(new java.awt.Dimension(176, 53));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("11");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlManual5Layout = new javax.swing.GroupLayout(pnlManual5);
        pnlManual5.setLayout(pnlManual5Layout);
        pnlManual5Layout.setHorizontalGroup(
            pnlManual5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlManual5Layout.setVerticalGroup(
            pnlManual5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlManual2Layout = new javax.swing.GroupLayout(pnlManual2);
        pnlManual2.setLayout(pnlManual2Layout);
        pnlManual2Layout.setHorizontalGroup(
            pnlManual2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManual5, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlManual2Layout.setVerticalGroup(
            pnlManual2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManual2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlManual5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlManual3.setBackground(new java.awt.Color(217, 160, 102));
        pnlManual3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlManual3.setForeground(new java.awt.Color(51, 51, 51));
        pnlManual3.setPreferredSize(new java.awt.Dimension(176, 53));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo de Victoria:");

        pnlManual6.setBackground(new java.awt.Color(217, 160, 102));
        pnlManual6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlManual6.setForeground(new java.awt.Color(51, 51, 51));
        pnlManual6.setPreferredSize(new java.awt.Dimension(176, 53));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Carton lleno");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlManual6Layout = new javax.swing.GroupLayout(pnlManual6);
        pnlManual6.setLayout(pnlManual6Layout);
        pnlManual6Layout.setHorizontalGroup(
            pnlManual6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlManual6Layout.setVerticalGroup(
            pnlManual6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlManual3Layout = new javax.swing.GroupLayout(pnlManual3);
        pnlManual3.setLayout(pnlManual3Layout);
        pnlManual3Layout.setHorizontalGroup(
            pnlManual3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManual6, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlManual3Layout.setVerticalGroup(
            pnlManual3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManual3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlManual6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlAutomatico2.setBackground(new java.awt.Color(217, 160, 102));
        pnlAutomatico2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlAutomatico2.setForeground(new java.awt.Color(51, 51, 51));
        pnlAutomatico2.setPreferredSize(new java.awt.Dimension(176, 48));

        btn_CerrarCarton.setBackground(new java.awt.Color(255, 255, 255));
        btn_CerrarCarton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btn_CerrarCarton.setForeground(new java.awt.Color(255, 255, 255));
        btn_CerrarCarton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cerrar.png"))); // NOI18N
        btn_CerrarCarton.setText("Cerrar");
        btn_CerrarCarton.setBorderPainted(false);
        btn_CerrarCarton.setContentAreaFilled(false);
        btn_CerrarCarton.setFocusPainted(false);
        btn_CerrarCarton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_CerrarCarton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_Focus_precionado.png"))); // NOI18N
        btn_CerrarCarton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_precionado.png"))); // NOI18N
        btn_CerrarCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarCartonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAutomatico2Layout = new javax.swing.GroupLayout(pnlAutomatico2);
        pnlAutomatico2.setLayout(pnlAutomatico2Layout);
        pnlAutomatico2Layout.setHorizontalGroup(
            pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
            .addGroup(pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAutomatico2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_CerrarCarton, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlAutomatico2Layout.setVerticalGroup(
            pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
            .addGroup(pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAutomatico2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_CerrarCarton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pnlManual1Layout = new javax.swing.GroupLayout(pnlManual1);
        pnlManual1.setLayout(pnlManual1Layout);
        pnlManual1Layout.setHorizontalGroup(
            pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlManual2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlManual3, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(pnlAutomatico2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlManual1Layout.setVerticalGroup(
            pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlManual2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManual3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAutomatico2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlManual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlManual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlCartonLayout = new javax.swing.GroupLayout(pnlCarton);
        pnlCarton.setLayout(pnlCartonLayout);
        pnlCartonLayout.setHorizontalGroup(
            pnlCartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLetras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCartonLayout.setVerticalGroup(
            pnlCartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCarton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCarton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CerrarCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarCartonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CerrarCartonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgResultados dialog = new DlgResultados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_CerrarCarton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_B1;
    private javax.swing.JPanel pnlAutomatico2;
    private javax.swing.JPanel pnlCarton;
    private javax.swing.JPanel pnlLetras;
    private javax.swing.JPanel pnlManual1;
    private javax.swing.JPanel pnlManual2;
    private javax.swing.JPanel pnlManual3;
    private javax.swing.JPanel pnlManual5;
    private javax.swing.JPanel pnlManual6;
    // End of variables declaration//GEN-END:variables
}
