/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Vistas;

import javax.swing.JOptionPane;
import Controladores.ControladorTombola;
import Modelo.Tombolas.TombolaObserver;

/**
 *
 * @author Marisol Alfaro
 */
public class PnlTombola extends javax.swing.JPanel implements TombolaObserver {
    private ControladorTombola controlador;

    /**
     * Creates new form PnlTombola
     */
    public PnlTombola(ControladorTombola controlador) {
        initComponents();
        this.controlador = controlador;
        controlador.agregarObserver(this);
        lblUltimoCantado.setText("-");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCarton = new javax.swing.JPanel();
        pnlLetras = new javax.swing.JPanel();
        lbl_B1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlAutomatico1 = new javax.swing.JPanel();
        txtIngresarNumero = new javax.swing.JTextField();
        pnlManual1 = new javax.swing.JPanel();
        pnlManual2 = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        pnlManual3 = new javax.swing.JPanel();
        btnCantar = new javax.swing.JButton();
        pnlAutomatico2 = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        pnlManual4 = new javax.swing.JPanel();
        lblUltimoCantado = new javax.swing.JLabel();

        pnlCarton.setBackground(new java.awt.Color(238, 195, 154));
        pnlCarton.setForeground(new java.awt.Color(238, 195, 154));

        pnlLetras.setBackground(new java.awt.Color(217, 160, 102));
        pnlLetras.setForeground(new java.awt.Color(217, 160, 102));

        lbl_B1.setBackground(new java.awt.Color(0, 0, 0));
        lbl_B1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 55)); // NOI18N
        lbl_B1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_B1.setText("TOMBOLA");

        javax.swing.GroupLayout pnlLetrasLayout = new javax.swing.GroupLayout(pnlLetras);
        pnlLetras.setLayout(pnlLetrasLayout);
        pnlLetrasLayout.setHorizontalGroup(
            pnlLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLetrasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_B1)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlLetrasLayout.setVerticalGroup(
            pnlLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLetrasLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lbl_B1)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(217, 160, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        pnlAutomatico1.setBackground(new java.awt.Color(217, 160, 102));
        pnlAutomatico1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlAutomatico1.setForeground(new java.awt.Color(51, 51, 51));
        pnlAutomatico1.setPreferredSize(new java.awt.Dimension(176, 48));

        txtIngresarNumero.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        txtIngresarNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIngresarNumero.setText("75");
        txtIngresarNumero.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlAutomatico1Layout = new javax.swing.GroupLayout(pnlAutomatico1);
        pnlAutomatico1.setLayout(pnlAutomatico1Layout);
        pnlAutomatico1Layout.setHorizontalGroup(
            pnlAutomatico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
            .addGroup(pnlAutomatico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAutomatico1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtIngresarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlAutomatico1Layout.setVerticalGroup(
            pnlAutomatico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
            .addGroup(pnlAutomatico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAutomatico1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtIngresarNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnlManual1.setBackground(new java.awt.Color(217, 160, 102));
        pnlManual1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlManual1.setForeground(new java.awt.Color(51, 51, 51));

        pnlManual2.setBackground(new java.awt.Color(217, 160, 102));
        pnlManual2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlManual2.setForeground(new java.awt.Color(51, 51, 51));

        btnGenerar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_NO_precionado.png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.setBorderPainted(false);
        btnGenerar.setContentAreaFilled(false);
        btnGenerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_precionado.png"))); // NOI18N
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlManual2Layout = new javax.swing.GroupLayout(pnlManual2);
        pnlManual2.setLayout(pnlManual2Layout);
        pnlManual2Layout.setHorizontalGroup(
            pnlManual2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlManual2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlManual2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnGenerar)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlManual2Layout.setVerticalGroup(
            pnlManual2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(pnlManual2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlManual2Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(btnGenerar)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlManual3.setBackground(new java.awt.Color(217, 160, 102));
        pnlManual3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlManual3.setForeground(new java.awt.Color(51, 51, 51));
        pnlManual3.setPreferredSize(new java.awt.Dimension(176, 53));

        btnCantar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnCantar.setForeground(new java.awt.Color(255, 255, 255));
        btnCantar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_NO_precionado.png"))); // NOI18N
        btnCantar.setText("Cantar");
        btnCantar.setBorderPainted(false);
        btnCantar.setContentAreaFilled(false);
        btnCantar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCantar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_precionado.png"))); // NOI18N
        btnCantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlManual3Layout = new javax.swing.GroupLayout(pnlManual3);
        pnlManual3.setLayout(pnlManual3Layout);
        pnlManual3Layout.setHorizontalGroup(
            pnlManual3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
            .addGroup(pnlManual3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlManual3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnCantar)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlManual3Layout.setVerticalGroup(
            pnlManual3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlManual3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlManual3Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(btnCantar)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlManual1Layout = new javax.swing.GroupLayout(pnlManual1);
        pnlManual1.setLayout(pnlManual1Layout);
        pnlManual1Layout.setHorizontalGroup(
            pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlManual2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlManual3, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        pnlManual1Layout.setVerticalGroup(
            pnlManual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlManual2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlManual3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAutomatico2.setBackground(new java.awt.Color(217, 160, 102));
        pnlAutomatico2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlAutomatico2.setForeground(new java.awt.Color(51, 51, 51));
        pnlAutomatico2.setPreferredSize(new java.awt.Dimension(176, 48));

        lblInfo.setBackground(new java.awt.Color(0, 0, 0));
        lblInfo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("Ultimo número cantado:");
        lblInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pnlManual4.setBackground(new java.awt.Color(217, 160, 102));
        pnlManual4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 195, 154), 3, true));
        pnlManual4.setForeground(new java.awt.Color(51, 51, 51));
        pnlManual4.setPreferredSize(new java.awt.Dimension(176, 53));

        lblUltimoCantado.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        lblUltimoCantado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUltimoCantado.setText("11");
        lblUltimoCantado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlManual4Layout = new javax.swing.GroupLayout(pnlManual4);
        pnlManual4.setLayout(pnlManual4Layout);
        pnlManual4Layout.setHorizontalGroup(
            pnlManual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUltimoCantado, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlManual4Layout.setVerticalGroup(
            pnlManual4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManual4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUltimoCantado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlAutomatico2Layout = new javax.swing.GroupLayout(pnlAutomatico2);
        pnlAutomatico2.setLayout(pnlAutomatico2Layout);
        pnlAutomatico2Layout.setHorizontalGroup(
            pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAutomatico2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlManual4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAutomatico2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblInfo)
                    .addContainerGap(140, Short.MAX_VALUE)))
        );
        pnlAutomatico2Layout.setVerticalGroup(
            pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAutomatico2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlManual4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAutomatico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAutomatico2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAutomatico2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlAutomatico1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlManual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlManual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAutomatico1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAutomatico2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCartonLayout = new javax.swing.GroupLayout(pnlCarton);
        pnlCarton.setLayout(pnlCartonLayout);
        pnlCartonLayout.setHorizontalGroup(
            pnlCartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLetras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCartonLayout.setVerticalGroup(
            pnlCartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCarton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCarton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        try{
            controlador.generarNumero();
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, "No se pudo generar un número: " + ex.getMessage(), "Error",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantarActionPerformed
        String texto = txtIngresarNumero.getText().replace(" ", "");
        
        if(texto.isEmpty()){
            JOptionPane.showMessageDialog(this, "Primero ingrese un numero", "Dato requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int numero;
        try{
            numero = Integer.parseInt(texto);
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero valido", "Formato incorrecto", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(numero < 1 || numero > 75){
            JOptionPane.showMessageDialog(this, "El numero debe estar entre 1 y 75", "Numero fuera de rango", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            controlador.ingresarNumeroManual(numero);
            txtIngresarNumero.setText("");
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(), "Número repetido",JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Ocurrió un error al cantar el número: " + ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);         
        }
    }//GEN-LAST:event_btnCantarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCantar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblUltimoCantado;
    private javax.swing.JLabel lbl_B1;
    private javax.swing.JPanel pnlAutomatico1;
    private javax.swing.JPanel pnlAutomatico2;
    private javax.swing.JPanel pnlCarton;
    private javax.swing.JPanel pnlLetras;
    private javax.swing.JPanel pnlManual1;
    private javax.swing.JPanel pnlManual2;
    private javax.swing.JPanel pnlManual3;
    private javax.swing.JPanel pnlManual4;
    private javax.swing.JTextField txtIngresarNumero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizarNumero(int numero) {
        lblUltimoCantado.setText(String.valueOf(numero));
    }
}
